name: publish-nuget

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'PackageVersion to publish (e.g., 1.2.3). If empty and no tag, a run-number version is used.'
        required: false

jobs:
  pack-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Determine package version
        id: version
        run: |
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            VERSION="${GITHUB_REF_NAME#v}"
          elif [[ -n "${{ github.event.inputs.version }}" ]]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            VERSION="1.0.${GITHUB_RUN_NUMBER}"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Pack
        run: |
          dotnet pack ./src/MultiDb.Extensions/MultiDb.Extensions.csproj -c Release -o ./out /p:PackageVersion=${{ env.VERSION }}

      - name: Publish to NuGet
        if: ${{ secrets.NUGET_API_KEY != '' }}
        run: |
            dotnet nuget push ./out/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
